CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY ,
    username VARCHAR(255) NOT NULL ,
    email VARCHAR(255) UNIQUE NOT NULL ,
    password VARCHAR(255) NOT NULL 
);

CREATE TABLE attendance(
     id INT AUTO_INCREMENT PRIMARY KEY ,
     user_id INT NOT NULL ,
     check_in TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     check_out TIMESTAMP  NULL ,
     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE 
);   